# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Alicia_First_Blog"

# 网页的标题
title: "The Life of a Female Engineer"
# 网站的主标题
name: "Science and Technology"
# 网站副标题
description: "In the field of science and technology, women can have the same creativity as men!"

# 分页配置
# 每页文章数量
paginate: 9

# 其它配置, 可忽略, 无需修改
permalink: /:title/
paginate_path: /page:num/
plugins:
  - jekyll-paginate

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
lazyimages: "disabled"
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
